### ISSUE TITLE
[meta] the links to create new GH issues don't seem to work

### ISSUE THREAD

**Issue by guillaumervls** [vinejs/vinejs.dev#13]
### Package version

N/A

### Describe the bug

Hi and thanks for the lib!

These links on the "new issue" page ⬇️ don't seem to work: they take you back to the exact same page. So you're stuck. (also it's the same thing with the [VineJS repo](https://github.com/vinejs/vine))

<img width="1188" alt="image" src="https://github.com/vinejs/vinejs.dev/assets/3765057/0edcec04-2b35-4316-a1a3-414acc792dd1">

Am I missing something?

**Comment by thetutlage** [comment]
Fixed
